# Generated by Django 5.0.3 on 2024-08-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='remaining_seats',
        ),
    ]
