# Generated by Django 5.0.3 on 2024-08-08 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0002_remove_bus_remaining_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='busapp.bus'),
        ),
        migrations.AddField(
            model_name='booking',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='busapp.route'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.CharField(default='Tester', max_length=100),
        ),
    ]
