# Generated by Django 5.0.3 on 2024-08-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0003_booking_booking_date_booking_bus_booking_route_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='seats',
            new_name='available_seats',
        ),
    ]
