# Generated by Django 5.0.3 on 2024-08-08 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0004_rename_seats_bus_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='routes',
            field=models.ManyToManyField(related_name='buses', to='busapp.route'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='busapp.bus'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='busapp.route'),
        ),
    ]
