# Generated by Django 5.0.3 on 2024-08-08 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0005_bus_routes_alter_booking_bus_alter_booking_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='routes',
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='busapp.route'),
        ),
    ]
