# Generated by Django 5.0.3 on 2024-08-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0006_remove_bus_routes_bus_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat_number',
        ),
    ]
