# Generated by Django 5.0.3 on 2024-08-08 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0007_remove_booking_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='travel_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
