# Generated by Django 5.0.3 on 2024-08-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0009_remove_booking_route_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(default='AVAILABLE', max_length=30),
        ),
    ]
