# Generated by Django 5.0.3 on 2024-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0010_route_price_alter_bus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
