# Generated by Django 5.1 on 2024-08-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0011_alter_route_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
