# Generated by Django 5.1 on 2024-08-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0013_customuser_userprofile_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat_number',
        ),
    ]
