# Generated by Django 5.1 on 2024-08-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0014_remove_booking_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
