# Generated by Django 5.1 on 2024-08-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0015_userprofile_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
