# Generated by Django 5.1 on 2024-08-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0017_customuser_id_number_userprofile_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
