# Generated by Django 5.1 on 2024-08-21 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0018_remove_userprofile_user_delete_customuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='route',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='busapp.route'),
        ),
    ]
