# Generated by Django 5.1 on 2024-08-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0019_booking_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=100, null=True, unique=True)),
                ('checkout_request_id', models.CharField(max_length=100, null=True, unique=True)),
                ('result_code', models.IntegerField(default=0, null=True)),
                ('result_description', models.CharField(max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('mpesa_receipt_number', models.CharField(max_length=100, null=True)),
                ('balance', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
