# Generated by Django 5.1 on 2024-08-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0020_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
